In [3]:
class complex:
    def __init__(self,real,img):
        self.real = real
        self.img = img
        
        
    def __add__(self,comp1):
        newreal = self.real + comp1.real
        newimg = self.img + comp1.img
        comp2 = complex(newreal,newimg)
        return comp2
        
        

In [7]:
c1 = complex(2,10)
c2 = complex(3,5)
c3 = c1+c2

print(c3.real,c3.img)

5 15


### NUMPY TUTORIAL

[http://cs231n.github.io/python-numpy-tutorial/](http://cs231n.github.io/python-numpy-tutorial/)

[official Documentation](https://docs.scipy.org/doc/numpy/reference/)


In [47]:
!pip install numpy

In [49]:
import numpy as np

In [51]:
arr = np.array([1,2,3,4,5,6])

In [52]:
arr

array([1, 2, 3, 4, 5, 6])

In [53]:
arr.shape

(6,)

In [54]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [55]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [56]:
np.full((10,10),9)

array([[9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

In [58]:
x = np.random.random((2,3))

In [59]:
x

array([[0.02717411, 0.66918654, 0.99615845],
       [0.25339971, 0.87814395, 0.43473465]])

In [63]:
x[:,0]

array([0.02717411, 0.25339971])

In [64]:
x = x+5

In [65]:
x

array([[5.02717411, 5.66918654, 5.99615845],
       [5.25339971, 5.87814395, 5.43473465]])

In [66]:
x = x-3

In [67]:
x

array([[2.02717411, 2.66918654, 2.99615845],
       [2.25339971, 2.87814395, 2.43473465]])

In [68]:
x = x*3

In [69]:
x

array([[6.08152232, 8.00755962, 8.98847534],
       [6.76019913, 8.63443186, 7.30420395]])

In [70]:
x = x/2

In [71]:
x

array([[3.04076116, 4.00377981, 4.49423767],
       [3.38009957, 4.31721593, 3.65210197]])

In [72]:
x = x**2

In [73]:
x

array([[ 9.24622843, 16.03025278, 20.19817222],
       [11.42507307, 18.6383534 , 13.33784882]])

In [77]:
x1 = np.full((3,3),10)
x2  = np.full((3,3),5)

In [78]:
x1

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [79]:
x2

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [80]:
x1+x2

array([[15, 15, 15],
       [15, 15, 15],
       [15, 15, 15]])

In [81]:
x1 - x2

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [82]:
x1 * x2

array([[50, 50, 50],
       [50, 50, 50],
       [50, 50, 50]])

In [83]:
x1.dot(x2)

array([[150, 150, 150],
       [150, 150, 150],
       [150, 150, 150]])

In [85]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [86]:
arr1.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [89]:
np.transpose(arr1)1


array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [90]:
arr1.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [93]:
np.eye(3,6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.]])

In [94]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [95]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [96]:
arr1[[0,1,2],[0,0,1]]

array([1, 4, 8])

In [97]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [98]:
arr1 < 5

array([[ True,  True,  True],
       [ True, False, False],
       [False, False, False]])

In [101]:
arr1[arr1<5]

array([1, 2, 3, 4])

In [103]:
np.array([1,2,3,4],dtype="int")

array([1, 2, 3, 4])

In [104]:
np.array([1,2,3,4],dtype="float")

array([1., 2., 3., 4.])

In [105]:
arr1.sum()

45

In [106]:
np.sum(arr1)

45

In [107]:
arr1.shape

(3, 3)

In [108]:
arr1.reshape((1,-1))

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [109]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])